on: 
  push:
    paths:
      - personal-site/**

env:
  AWS_ACCESS_KEY_ID : ${{ secrets.TF_VAR_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.TF_VAR_SECRET_KEY }}

jobs:
  check:
    name: Check files
    outputs:
      terraform-changes: ${{ steps.check_files.outputs.terraform-changes }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt

          all_in_infra=true
          while IFS= read -r file
          do
            echo "$file"
            if [[ $file != personal-site/infrastructure/* ]]; then
              all_in_infra=false
              break
            fi
          done < files.txt

          echo "terraform-changes=$all_in_infra" >> $GITHUB_OUTPUT

  terraform_apply_and_plan:
    name: Build Infrastructure via Terraform
    needs: check
    if: ${{ needs.check.outputs.terraform-changes == 'true' }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.TF_VAR_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.TF_VAR_SECRET_KEY }}
    defaults:
      run:
        working-directory: ./personal-site/infrastructure
    steps:
      - uses: hashicorp/setup-terraform@v3
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run for 'infrastructure' folder
        run: |
          # echo "This job runs only when all modified files are under the 'infrastructure' folder."
          # echo "terraform-changes: ${{ needs.check.outputs.terraform-changes }}"
          pwd

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

  push_website_code_to_s3:
    name: Push Website Code to S3 Bucket
    needs: terraform_apply_and_plan
    if: always() && needs.terraform_apply_and_plan.result == 'success' || needs.terraform_apply_and_plan.result == 'failure' || needs.terraform_apply_and_plan.result == 'skipped'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.TF_VAR_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.TF_VAR_SECRET_KEY }}
    defaults:
      run:
        working-directory: ./personal-site/web-code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TF_VAR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_VAR_SECRET_KEY }}
          aws-region: eu-west-2
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp . s3://stejackson.com --recursive
